### ISSUE TITLE
Istio-pilot cannot be removed by juju remove-application

### ISSUE THREAD

**Issue by i-chvets** [canonical/istio-operators#292] opened 2023-06-22 18:00 UTC
# Description
Istio-pilot cannot be removed by juju remove-application
To reproduces:
```
juju deploy istio-pilot --trust --channel latest/edge
juju deploy istio-gateway --trust --config kind=ingress istio-ingressgateway --channel latest/edge
juju relate istio-pilot istio-ingressgateway
juju remove-application istio-ingressgateway
juju remove-application istio-pilot
juju status
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  2.9.43   unsupported  14:00:46-04:00

App          Version  Status  Scale  Charm        Channel      Rev  Address        Exposed  Message
istio-pilot           error     1/0  istio-pilot  latest/edge  550  10.152.183.74  no       hook failed: "remove"

Unit            Workload  Agent  Address     Ports  Message
istio-pilot/0*  error     idle   10.1.59.74         hook failed: "remove"

```

**Comment by ca-scribner** [comment] 2023-07-05 13:40
Might be related or duplicate of #189 

This should be an easy to fix issue given recent upgrades to chisme.  Should be able to use the KubernetesResourceHandler's delete methods to remove things more robustly.

**Comment by ca-scribner** [comment] 2023-07-11 12:36
May or may not be the exact same bug, but this was hit recently with these logs:

```
2023-07-11T12:14:02.817Z [container-agent] 2023-07-11 12:14:02 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "remove" hook
2023-07-11T12:14:03.026Z [container-agent] 2023-07-11 12:14:03 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "remove" hook
2023-07-11T12:14:03.300Z [container-agent] 2023-07-11 12:14:03 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "remove" hook
2023-07-11T12:14:03.813Z [container-agent] 2023-07-11 12:14:03 ERROR juju-log ApiError encountered while attempting to delete resource.
2023-07-11T12:14:03.813Z [container-agent] Traceback (most recent call last):
2023-07-11T12:14:03.813Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 182, in raise_for_status
2023-07-11T12:14:03.813Z [container-agent]     resp.raise_for_status()
2023-07-11T12:14:03.813Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/httpx/_models.py", line 749, in raise_for_status
2023-07-11T12:14:03.813Z [container-agent]     raise HTTPStatusError(message, request=request, response=self)
2023-07-11T12:14:03.813Z [container-agent] httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://10.96.0.1/api/v1/namespaces/kubeflow/serviceaccounts/istio-ingressgateway-workload-service-account'
2023-07-11T12:14:03.813Z [container-agent] For more information check: https://httpstatuses.com/404
2023-07-11T12:14:03.813Z [container-agent] 
2023-07-11T12:14:03.813Z [container-agent] During handling of the above exception, another exception occurred:
2023-07-11T12:14:03.813Z [container-agent] 
2023-07-11T12:14:03.813Z [container-agent] Traceback (most recent call last):
2023-07-11T12:14:03.813Z [container-agent]   File "./src/charm.py", line 97, in remove
2023-07-11T12:14:03.813Z [container-agent]     self.lightkube_client.delete(
2023-07-11T12:14:03.813Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/client.py", line 73, in delete
2023-07-11T12:14:03.813Z [container-agent]     return self._client.request("delete", res=res, name=name, namespace=namespace)
2023-07-11T12:14:03.813Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 239, in request
2023-07-11T12:14:03.813Z [container-agent]     return self.handle_response(method, resp, br)
2023-07-11T12:14:03.813Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 190, in handle_response
2023-07-11T12:14:03.813Z [container-agent]     self.raise_for_status(resp)
2023-07-11T12:14:03.813Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 184, in raise_for_status
2023-07-11T12:14:03.813Z [container-agent]     raise transform_exception(e)
2023-07-11T12:14:03.813Z [container-agent] lightkube.core.exceptions.ApiError: serviceaccounts "istio-ingressgateway-workload-service-account" not found
2023-07-11T12:14:03.823Z [container-agent] 2023-07-11 12:14:03 ERROR juju-log serviceaccounts "istio-ingressgateway-workload-service-account" not found
2023-07-11T12:14:03.842Z [container-agent] 2023-07-11 12:14:03 ERROR juju-log Uncaught exception while in charm code:
2023-07-11T12:14:03.843Z [container-agent] Traceback (most recent call last):
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 182, in raise_for_status
2023-07-11T12:14:03.843Z [container-agent]     resp.raise_for_status()
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/httpx/_models.py", line 749, in raise_for_status
2023-07-11T12:14:03.843Z [container-agent]     raise HTTPStatusError(message, request=request, response=self)
2023-07-11T12:14:03.843Z [container-agent] httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://10.96.0.1/api/v1/namespaces/kubeflow/serviceaccounts/istio-ingressgateway-workload-service-account'
2023-07-11T12:14:03.843Z [container-agent] For more information check: https://httpstatuses.com/404
2023-07-11T12:14:03.843Z [container-agent] 
2023-07-11T12:14:03.843Z [container-agent] During handling of the above exception, another exception occurred:
2023-07-11T12:14:03.843Z [container-agent] 
2023-07-11T12:14:03.843Z [container-agent] Traceback (most recent call last):
2023-07-11T12:14:03.843Z [container-agent]   File "./src/charm.py", line 141, in <module>
2023-07-11T12:14:03.843Z [container-agent]     main(Operator)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/ops/main.py", line 426, in main
2023-07-11T12:14:03.843Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
2023-07-11T12:14:03.843Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/ops/framework.py", line 276, in emit
2023-07-11T12:14:03.843Z [container-agent]     framework._emit(event)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/ops/framework.py", line 736, in _emit
2023-07-11T12:14:03.843Z [container-agent]     self._reemit(event_path)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/ops/framework.py", line 783, in _reemit
2023-07-11T12:14:03.843Z [container-agent]     custom_handler(event)
2023-07-11T12:14:03.843Z [container-agent]   File "./src/charm.py", line 97, in remove
2023-07-11T12:14:03.843Z [container-agent]     self.lightkube_client.delete(
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/client.py", line 73, in delete
2023-07-11T12:14:03.843Z [container-agent]     return self._client.request("delete", res=res, name=name, namespace=namespace)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 239, in request
2023-07-11T12:14:03.843Z [container-agent]     return self.handle_response(method, resp, br)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 190, in handle_response
2023-07-11T12:14:03.843Z [container-agent]     self.raise_for_status(resp)
2023-07-11T12:14:03.843Z [container-agent]   File "/var/lib/juju/agents/unit-istio-ingressgateway-0/charm/venv/lightkube/core/generic_client.py", line 184, in raise_for_status
2023-07-11T12:14:03.843Z [container-agent]     raise transform_exception(e)
2023-07-11T12:14:03.843Z [container-agent] lightkube.core.exceptions.ApiError: serviceaccounts "istio-ingressgateway-workload-service-account" not found
2023-07-11T12:14:04.095Z [container-agent] 2023-07-11 12:14:04 ERROR juju.worker.uniter.operation runhook.go:153 hook "remove" (via hook dispatching script: dispatch) failed: exit status 1
2023-07-11T12:14:04.096Z [container-agent] 2023-07-11 12:14:04 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "remove" hook
2023-07-11T12:14:04.149Z [container-agent] 2023-07-11 12:14:04 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "remove" hook
2023-07-11T12:14:04.233Z [container-agent] 2023-07-11 12:14:04 INFO juju.worker.uniter resolver.go:155 awaiting error resolution for "remove" hook
```

Seems like, at least sometimes, we have a race condition on deletion.  In other charms we've adopted the "try to delete, but ignore 404 errors" approach and we should use that here too

**Comment by NohaIhab** [comment] 2023-07-26 13:52
As mentioned above, using `kubernetesresourcehandler.delete()` or latest chisme `chisme.batch.delete_many()` should fix this issue, both skip 404 errors by default.

**Comment by ca-scribner** [comment] 2023-07-26 14:21
This should be a pretty quick fix.  Some options are:

* [this code](https://github.com/canonical/istio-operators/blob/6c1e58db3626d8cccf4c809e128f8a9f7446f6c7/charms/istio-pilot/src/istioctl.py#L97) provides an unused `remove` method that could be used in our charm's `on_remove` event handler.  
* [KubernetesResourceHandler.delete](https://github.com/canonical/charmed-kubeflow-chisme/blob/c82bd1dd21b375c6cf91f43298fdc09d98e4e07c/src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py#L144) was added recently and it might be a better way to delete everything without having to re-render the manifests.  To use it, we'd probably want to change how we deploy resources to run that through the KubernetesResourceHandler as well

**Closed** 2023-08-24 13:45 UTC
Labels: bug, Kubeflow 1.8
